# Generated by Django 5.2.1 on 2025-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='successful_events',
            field=models.IntegerField(default=0),
        ),
    ]
